#!/bin/bash

FONT_FACE="FiraCode Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

SPACE_TYPE=$(yabai -m query --spaces --space | jq .type | tr -d '"')

if [[ $SPACE_TYPE = 'float' ]]; then
	ICON=󰉪
else
	ICON=
fi

sketchybar --bar \
	height=32 \
	color=0xcc1a1a26 \
	margin=0 \
	corner_radius=0 \
	sticky=on \
	padding_left=8 \
	padding_right=8 \
	notch_width=188 \
	display=all

sketchybar --default \
	background.color=0xcc74747a \
	background.corner_radius=5 \
	background.padding_right=5 \
	background.height=26 \
	icon.font="$FONT_FACE:Medium:15.0" \
	icon.padding_left=5 \
	icon.padding_right=5 \
	label.font="$FONT_FACE:Medium:12.0" \
	label.color=0xffcad3f5 \
	label.y_offset=0 \
	label.padding_left=0 \
	label.padding_right=5

# left - left
sketchybar --add item space left \
	--set space \
	icon="$ICON" \
	background.color=0x00ffffff \
	icon.color=0xffffffff \
	background.padding_right=4 \
	background.padding_left=4 \
	script="$PLUGIN_DIR/space.sh" \
	click_script="sketchybar --update"

# left - right
sketchybar --add item front_app q \
	--set front_app \
	background.color=0xccb1d99c \
	background.padding_left=0 \
	background.padding_right=0 \
	icon.color=0xff24273a \
	icon.padding_right=6 \
	icon.padding_left=6 \
	label.drawing=off \
	script="$PLUGIN_DIR/front_app.sh"

sketchybar --add item front_app.name q \
	--set front_app.name \
	background.padding_left=8 \
	background.padding_right=4 \
	icon.padding_left=4 \
	icon.padding_right=0 \
	label.font="$FONT_FACE:Bold:12.0" \
	label.padding_left=6 \
	label.padding_right=10 \
	label.drawing=yes

sketchybar --add bracket \
	front_app \
	front_app.name \
	--subscribe front_app front_app_switched

# right - left
sketchybar --add item weather.moon e \
	--set weather.moon \
	background.color=0xcc66ccff \
	background.padding_left=2 \
	background.padding_right=4 \
	icon.color=0xff181926 \
	icon.font="$FONT_FACE:Bold:22.0" \
	icon.padding_left=4 \
	icon.padding_right=3 \
	label.drawing=off \
	label.padding_left=0 \
	label.padding_right=0 \
	--subscribe weather.moon mouse.clicked

sketchybar --add item weather e \
	--set weather \
	update_freq=1800 \
	label.padding_right=10 \
	script="$PLUGIN_DIR/weather.sh" \
	--subscribe weather system_woke

# right - right
sketchybar --add item clock right \
	--set clock \
	icon=󰃰 \
	icon.color=0xffed8796 \
	update_freq=10 \
	script="$PLUGIN_DIR/clock.sh"

sketchybar --add item battery right \
	--set battery \
	update_freq=20 \
	script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
	--set volume \
	icon.color=0xff8aadf4 \
	label.drawing=true \
	script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change

sketchybar --update
sketchybar --trigger space_change

echo "sketchybar configuation loaded.."
