## mechanics
macos_option_as_alt yes
allow_remote_control yes
listen_on unix:/tmp/mykitty

## color - load from theme file (synced by nvim)
include theme-dark.conf

## font
font_family JetBrainsMono Nerd Font
font_size 15.5

## line height
adjust_line_height 10

## background
background_tint 0.98
background_image_layout cscaled
background_opacity 0.95

## Shortcuts
map cmd+equal change_font_size current +1.0
map cmd+minus change_font_size current -1.0
map cmd+0 change_font_size current 0
# map alt-s to cmd-s
map cmd+s send_text all \x1bs

cursor_trail 1
cursor_trail_start_threshold 0
