# Everforest Light Medium
cursor none
foreground              #5c6a72
background              #fdf6e3
selection_foreground    #fdf6e3
selection_background    #5c6a72
scrollbar_handle_color  #939f91
scrollbar_track_color   #e6e2cc
url_color               #35a77c
active_border_color     #8da101
inactive_border_color   #939f91
bell_border_color       #dfa000
active_tab_foreground   #fdf6e3
active_tab_background   #8da101
inactive_tab_foreground #5c6a72
inactive_tab_background #efebd4
tab_bar_background      #efebd4
mark1_foreground #fdf6e3
mark1_background #8da101
mark2_foreground #fdf6e3
mark2_background #35a77c
mark3_foreground #fdf6e3
mark3_background #3a94c5
color0  #5c6a72
color8  #939f91
color1  #f85552
color9  #f85552
color2  #8da101
color10 #8da101
color3  #dfa000
color11 #dfa000
color4  #3a94c5
color12 #3a94c5
color5  #df69ba
color13 #df69ba
color6  #35a77c
color14 #35a77c
color7  #e6e2cc
color15 #efebd4
