#!/usr/bin/env sh
## https://github.com/koekeishiya/skhd/issues/1

# start or stop yabai
shift + alt - y: yabai --stop-service || yabai --start-service

# focus window
cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

# swap window
shift + alt - h : yabai -m window --swap west
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - l : yabai -m window --swap east

# increase window size
shift + alt - left : yabai -m window --resize left:-20:0
shift + alt - down : yabai -m window --resize bottom:0:20
shift + alt - up : yabai -m window --resize top:0:-20
shift + alt - right : yabai -m window --resize right:20:0

# decrease window size
shift + cmd - left : yabai -m window --resize left:20:0
shift + cmd - down : yabai -m window --resize bottom:0:-20
shift + cmd - up : yabai -m window --resize top:0:20
shift + cmd - right : yabai -m window --resize right:-20:0

# toggle float
alt - t : ~/dotfiles/yabai/sh/float.sh

# toggle fullscreen
ctrl + alt - return : yabai -m window --toggle zoom-fullscreen

# balance size of windows
shift + alt - 0 : yabai -m space --balance

# toggle window border
shift - space : yabai -m window --toggle border

# toggle window split type
alt - e : yabai -m window --toggle split

# mirror tree y-axis
alt - y : yabai -m space --mirror y-axis

# focus desktop
ctrl + alt - 1 : yabai -m space --focus 1
ctrl + alt - 2 : yabai -m space --focus 2
ctrl + alt - 3 : yabai -m space --focus 3
ctrl + alt - 4 : yabai -m space --focus 4
ctrl + alt - 5 : yabai -m space --focus 5
ctrl + alt - 6 : yabai -m space --focus 6
ctrl + alt - 7 : yabai -m space --focus 7
ctrl + alt - 8 : yabai -m space --focus 8
ctrl + alt - 9 : yabai -m space --focus 9
ctrl - left : yabai -m space --focus prev || yabai -m space --focus last
ctrl - right : yabai -m space --focus next || yabai -m space --focus first

# send current window to another space
cmd + alt - 1 : yabai -m window --space 1 && yabai -m space --focus 1
cmd + alt - 2 : yabai -m window --space 2 && yabai -m space --focus 2
cmd + alt - 3 : yabai -m window --space 3 && yabai -m space --focus 3
cmd + alt - 4 : yabai -m window --space 4 && yabai -m space --focus 4
cmd + alt - 5 : yabai -m window --space 5 && yabai -m space --focus 5
cmd + alt - 6 : yabai -m window --space 6 && yabai -m space --focus 6
cmd + alt - 7 : yabai -m window --space 7 && yabai -m space --focus 7
cmd + alt - 8 : yabai -m window --space 8 && yabai -m space --focus 8
cmd + alt - 9 : yabai -m window --space 9 && yabai -m space --focus 9

# stack
alt - s : ~/dotfiles/yabai/sh/stack.sh
alt - d : yabai -m window --focus stack.next || yabai -m window --focus stack.first
