#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_border off
yabai -m config active_window_border_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
gap=6
top_gap=4
yabai -m config layout bsp
yabai -m config top_padding $top_gap
yabai -m config bottom_padding $gap
yabai -m config left_padding $gap
yabai -m config right_padding $gap
yabai -m config window_gap $gap

ignore_app="^(访达|微信|系统设置)$"
yabai -m rule --add app="$ignore_app" manage=off

echo "yabai configuration loaded.."
