# Everforest Light
set -g mode-style "fg=#5c6a72,bg=#e6e2cc"
set -g message-style "fg=#5c6a72,bg=#e6e2cc"
set -g message-command-style "fg=#5c6a72,bg=#e6e2cc"
set -g pane-border-style "fg=#e0dcc7"
set -g pane-active-border-style "fg=#8da101"
set -g status-style "fg=#5c6a72,bg=#f3ead3"
set -g status-right "#[fg=#8da101,bg=#f3ead3,nobold,nounderscore,noitalics]#[fg=#f3ead3,bg=#8da101]#($HOME/dotfiles/tmux/status_time.sh) "
setw -g window-status-activity-style "underscore,fg=#5c6a72,bg=#f3ead3"
setw -g window-status-style "NONE,fg=#5c6a72,bg=#e6e2cc"
setw -g window-status-format "#[fg=#f3ead3,bg=#a6b0a0]#[fg=#f3ead3,reverse]#[none]#I #[fg=#5c6a72,bg=#e6e2cc] #W #[fg=#f3ead3,reverse]#[none]"
setw -g window-status-current-format "#[fg=#f3ead3,bg=#8da101]#[fg=#f3ead3,reverse]#[none]#I #[fg=#5c6a72,bg=#dfd9c1,bold] #W #[fg=#f3ead3,reverse]#[none]"
